Fix cgroup/frontier/memory.min: Permission denied issue

diff --git a/report/run_base b/report/run_base
--- a/report/run_base
+++ b/report/run_base
@@ -23,7 +23,15 @@ fi
 
 rm -rf $benchmark_root/../output/$test_name
 docker rm -f $container_name 2>/dev/null
-docker run --name $container_name --init --privileged -v /z/nikos/tmp:/tmp hs/${benchmark_name} ./report/benchmarks/${test_name}/run $@
+if [ -d /sys/fs/cgroup/frontier ]; then
+    if [ -w /sys/fs/cgroup/frontier/memory.min ]; then
+        rmdir /sys/fs/cgroup/frontier
+    else
+        echo "Permission denied: Unable to remove /sys/fs/cgroup/frontier"
+        exit 1
+    fi
+fi
+docker run --name $container_name --init --privileged --cgroupns=host -v /z/nikos/tmp:/tmp hs/${benchmark_name} ./report/benchmarks/${test_name}/run $@
 mkdir -p $benchmark_root/../output/$test_name
 docker cp $container_name:/srv/hs/report/output/$test_name/error $benchmark_root/../output/$test_name/error
 docker cp $container_name:/srv/hs/report/output/$test_name/hs_time $benchmark_root/../output/$test_name/hs_time
